apiVersion: v1
kind: Service
metadata:
  labels:
    app: hacbs-jvm-operator
  name: hacbs-jvm-operator-monitor
  namespace: jvm-build-service
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: probes
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: hacbs-jvm-operator
  sessionAffinity: None
  type: ClusterIP
