apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hacbs-jvm-operator-monitor
  namespace: jvm-build-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hacbs-jvm-operator-monitor
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hacbs-jvm-operator-monitor
  namespace: jvm-build-service
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
